image: node:17.3.0

pipelines:
  pull-requests:
    '**': # All branches
      - step:
          caches:
            - node
          name: Build and Test
          script:
            - echo "Installing dependencies..."
            - npm install
            - echo "Testing..."
            - npm run test
