export const exampleBusinessLocations = [
  {
    addressLine1: '1234 Business St',
    addressLine2: 'Unit 3',
    postal: 'A1A1A1',
    city: 'Victoria',
    email: 'Owner@mybusiness.com',
    phone: '250-222-3456',
    underage: 'Underage Permitted',
    health_authority: 'Island Health',
    manufacturing: 'No',
  },
  {
    addressLine1: '789 Main St',
    addressLine2: 'Unit 5',
    postal: 'A1A1A1',
    city: 'Vancouver',
    email: 'support@company.com',
    phone: '111-222-3456',
    underage: 'No',
    health_authority: 'Interior Health',
    manufacturing: 'Yes',
  },
  {
    addressLine1: '111 Pine Ave',
    addressLine2: '111 Pine Ave',
    postal: 'A1A1A1',
    city: 'Burnaby',
    email: 'resourcing@emailprovider.com',
    phone: '123-456-7890',
    underage: 'Yes',
    health_authority: 'Fraser Health',
    manufacturing: 'No',
  },
  {
    addressLine1: '7 Park Pl',
    addressLine2: 'Unit 9',
    postal: 'A1A1A1',
    city: 'Prince Rupert',
    email: 'Owner@mybusiness.com',
    phone: '1112223456',
    underage: 'None Permitted',
    health_authority: 'Northern Health',
    manufacturing: 'Yes',
  },
  {
    addressLine1: '1 Industrial Plaza',
    addressLine2: 'Building 2',
    postal: 'A1A1A1',
    city: 'Vancouver',
    email: 'me@myemail.com',
    phone: '1234567890',
    underage: 'No',
    health_authority: 'Vancouver Coastal Health',
    manufacturing: 'Yes',
  },
]

export const exampleProductReport = [
  {
    type: 'E-cigarette',
    brandName: 'Best E-cigarettes',
    productName: 'quick-vape',
    manufacturerName: 'Vapes R Us',
    manufacturerContact: 'Jim',
    manufacturerAddress: '1234 Main st. Vancouver, BC',
    manufacturerPhone: '123-456-7890',
    manufacturerEmail: 'contact@bestEcigarettes.com',
    concentration: '12 mg/mL',
    containerCapacity: '30 mL',
    cartridgeCapacity: '30 mL',
    ingredients: 'Propylene Glycol, Vegetable Glycerine, flavoring 1, flavoring 2, Nicotine',
    flavour: 'Grape',
  },
  {
    type: 'E-juice',
    brandName: 'Best Vape',
    productName: 'Traditional Tobacco',
    manufacturerName: 'Global Vapor',
    manufacturerContact: 'Tim G',
    manufacturerAddress: '1234 Example st. Toronto, Ontario',
    manufacturerPhone: '1112223456',
    manufacturerEmail: 'manufacturer@globalVapor.com',
    concentration: '50 mg/mL',
    containerCapacity: '60 mL',
    cartridgeCapacity: '60 mL',
    ingredients: 'Propylene Glycol, Vegetable Glycerine, flavoring 1, Citric acid, Sucralose, Nicotine',
    flavour: 'Tobacco',
  },
  {
    type: 'Tank',
    brandName: 'Tanks Today',
    productName: 'Tank model X',
    manufacturerName: 'Fancy Tanks',
    manufacturerContact: 'Bob Smith',
    manufacturerAddress: '1234 Tank st. Victoria, BC',
    manufacturerPhone: '1234567890',
    manufacturerEmail: 'support@manufacturer.com',
    concentration: 'N/A',
    containerCapacity: '3 mL',
    cartridgeCapacity: '3 mL',
    ingredients: 'N/A',
    flavour: 'N/A',
  },
  {
    type: 'Battery operated device',
    brandName: 'My Mod',
    productName: 'Mod II Platinum',
    manufacturerName: 'ModWorld',
    manufacturerContact: 'Sam R MacDonald',
    manufacturerAddress: '1234 5th St. Calgary, Alberta',
    manufacturerPhone: '1112223456',
    manufacturerEmail: 'support@manufacturer.com',
    concentration: 'N/A',
    containerCapacity: 'N/A',
    cartridgeCapacity: 'N/A',
    ingredients: 'N/A',
    flavour: 'N/A',
  },
  {
    type: 'Device and tank package',
    brandName: 'Complete vape',
    productName: 'All in one vaping kit',
    manufacturerName: 'All your vaping needs',
    manufacturerContact: 'Kathy T',
    manufacturerAddress: '1234 S. North st. Victoria, BC',
    manufacturerPhone: '1234567890',
    manufacturerEmail: 'support@manufacturer.com',
    concentration: 'N/A',
    containerCapacity: '3 mL',
    cartridgeCapacity: '3 mL',
    ingredients: 'N/A',
    flavour: 'N/A',
  },
  {
    type: 'Disposable cartridge',
    brandName: 'EZvape',
    productName: 'use-n-throw',
    manufacturerName: 'Quick vapor',
    manufacturerContact: 'Victoria M',
    manufacturerAddress: '1234 West st. Vancouver, BC',
    manufacturerPhone: '1234567890',
    manufacturerEmail: 'support@manufacturer.com',
    concentration: '20 mg/mL',
    containerCapacity: '5 mL',
    cartridgeCapacity: '5 mL',
    ingredients: 'Propylene Glycol, Vegetable Glycerine, flavoring 1, Citric acid, Sucralose, Nicotine',
    flavour: 'Mint',
  },
]