name: AWS Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      migrations:
        description: 'Run database migrations'
        type: boolean
        required: true
      frontends:
        description: 'Deploy frontends'
        type: boolean
        required: true
      version:
        description: 'Version Number'
        required: false
      zap_scan:
        description: 'Run ZAP Scan'
        type: boolean
        required: false
jobs:
  nothing:
    name: nothing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
