name: Dev-Workflow
on:
  workflow_dispatch:
    inputs:
       environment:
        description: 'Environment to run tests against' 
        type: environment 
        required: true
       version:
        description: 'Version Number'
        required: false
  push: 
    branches:
      - main
  pull_request:
  
concurrency: dev

env:
  APP_IMAGE: ${{ secrets.APP_IMAGE }} 
  IMAGE_ID: ${{ secrets.AWS_ECR_URI }}
  IMAGE_NAME: fmdbtest
  TF_VERSION: 1.2.2
  TG_VERSION: 0.37.1
  TG_SRC_PATH: Terraform
  TFC_WORKSPACE: dev
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build_jobs: 
    name: build jobs 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Copy env file
        run: |
          cd packages/bcer-retailer-app
          cp .config/.env.aws.dev app/.env
          cd app        
      - name: Build project
        run: |
          cd packages/bcer-retailer-app/app
          npm install 
          npm run build 
  
  docker_push:
    name: docker push
    environment:  dev
    runs-on: ubuntu-22.04
    needs: build_jobs
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: FEATURE/aws
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: packages/bcer-api/app/Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID  }}${{env.IMAGE_NAME}}
          
  terraform_apply:
    name: terraform apply 
    environment: dev
    runs-on: ubuntu-22.04
    needs: docker_push
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1
          
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          
      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
            
      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{env.TFC_WORKSPACE }}
        env:
          app_image: ${{ env.IMAGE_ID }}:${{ github.sha }}
          LICENSE_PLATE: ${{ secrets.MY_LICENSE_PLATE }}
        run: |
            echo "repository variable : '${{ vars.ENVIRONMENT }}' " 
            echo "Environment variable: '${{ github.event.inputs.environment }}' " 
            terragrunt run-all apply --terragrunt-non-interactive

  deploy:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
    - uses: actions/checkout@master
    - name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
        aws-region: ca-central-1
    - name: Upload to S3
      run: |
        aws s3 sync "https://github.com/bcgov/moh-bcer/tree/FEATURE/aws/packages/bcer-retailer-app" s3://${{ secrets.AWS_S3_BUCKET }} --delete 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: ca-central-1


  # zap_scan:
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   name: Scan the webapplication
  #   needs: terraform_apply
  #   steps:
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.7.0
  #       with:
  #         target: 'https://fmdb.ynr9ed-dev.nimbus.cloud.gov.bc.ca/'
#   ----------------------------Commenting out while trying to get rollback working-------------------------------          
#   bump_version:
#     runs-on: ubuntu-22.04
#     permissions: write-all

#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: '0'

#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.59.0 # Don't use @master unless you're happy to test the latest version
#       env:
#         DEFAULT_BUMP: major
#         DEFAULT_BRANCH: main
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         RELEASE_BRANCHES : main
#         WITH_V: true
