name: Dev-Workflow
on:
  workflow_dispatch:
    inputs:
       environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
       version:
        description: 'Version Number'
        required: false
jobs:
  nothing:
    name: nothing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
